[package]
name = "host"
version = "0.1.0"
edition = "2021"
license = "Unlicense OR MIT"

[dependencies]
wasmtime_serde_host = "0.1.0"
serde = {version = "1.0.152", features = ["derive"]}

[profile.release]
opt-level = "z"
codegen-units = 1
lto = true
strip = true